version: '3.7'
services:

  postgres-crediya-auth:
    container_name: postgres-crediya-auth
    image: postgres:13.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - ./modules/crediya-auth/setup/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/postgres-crediya-auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crediya-backend

#  crediya-auth:
#    container_name: crediya-auth
#    build:
#      context: modules/crediya-auth
#      dockerfile: deployment/Dockerfile
#    image: crediya-auth:1.0.0
#    networks:
#      - crediya-backend
#    depends_on:
#      - postgres-crediya-auth
#    ports:
#      - "8081:8080"

  postgres-crediya-applications:
    container_name: postgres-crediya-applications
    image: postgres:13.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - ./modules/crediya-applications/setup/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/postgres-crediya-applications:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - crediya-backend

#  crediya-applications:
#    container_name: crediya-applications
#    build:
#      context: modules/crediya-applications
#      dockerfile: deployment/Dockerfile
#    image: crediya-applications:1.0.0
#    networks:
#      - crediya-backend
#    depends_on:
#      - postgres-crediya-applications
#    ports:
#      - "8082:8080"

networks:
  crediya-backend:
    driver: bridge
