- name: Configure environment
  hosts: localhost
  become: no
  vars_files:
    - "../inventory/{{ environment }}.yml"
  tasks:
    - name: Configure crediya-auth
      template:
        src: ../templates/modules/crediya-auth/.env.j2
        dest: ../../modules/crediya-auth/.env

    - name: Configure crediya-auth database
      template:
        src: ../templates/modules/crediya-auth/setup/setup.sql.j2
        dest: ../../modules/crediya-auth/setup/setup.sql

    - name: Configure crediya-applications
      template:
        src: ../templates/modules/crediya-applications/.env.j2
        dest: ../../modules/crediya-applications/.env

    - name: Configure crediya-applications database
      template:
        src: ../templates/modules/crediya-applications/setup/setup.sql.j2
        dest: ../../modules/crediya-applications/setup/setup.sql

    - name: Configure crediya-reporting
      template:
        src: ../templates/modules/crediya-reporting/.env.j2
        dest: ../../modules/crediya-reporting/.env
