version: '3.7'
services:

  postgres-crediya-auth:
    container_name: postgres-crediya-auth
    image: postgres:13.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  postgres-crediya-applications:
    container_name: postgres-crediya-applications
    image: postgres:13.0
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
